### ISSUE TITLE
Model Conversion Not Work

### ISSUE THREAD

**Issue by BeIanChang** [shubham0204/Depth-Anything-Android#3]
I wonder how author converted the model into onnx format. I utilized the [referenced project](https://github.com/fabio-sim/Depth-Anything-ONNX) , but the output model is quite different from the ones in the /assets of this project.

A quick comparison of models in Netron:
The author's:
<img width="1344" alt="截屏2024-03-01 13 42 10" src="https://github.com/shubham0204/Depth-Anything-Android/assets/131738692/4406a4f0-aead-44dc-a05f-8d4f65b935e9">
My output produced by [referenced project](https://github.com/fabio-sim/Depth-Anything-ONNX):
<img width="1425" alt="截屏2024-03-01 13 45 51" src="https://github.com/shubham0204/Depth-Anything-Android/assets/131738692/be17daf1-9ca1-4978-81b5-4963d4c61f2a">

**Comment by shubham0204** [comment]
@BeIanChang I've worked on the ONNX models taken from `Depth-Anything-ONNX`, thereby adding pre/post-processing operations in the same ONNX model. I'll soon share those scripts in the repository.

**Comment by shubham0204** [comment]
@BeIanChang This is the notebook that contains the code used to fuse pre/post-processing operations for `Depth-Anything` into a single ONNX model, which is used in the app as `model.onnx`: https://github.com/shubham0204/Google_Colab_Notebooks/blob/main/Depth_Anything_FusedOps_ONNX_Model.ipynb
